name: scheduled-scrape
on:
  schedule:
    - cron: '0 */6 * * *'    # every 6 hours
  workflow_dispatch:

jobs:
  call-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Call scrape endpoint
        env:
          BASE_URL: ${{ secrets.APP_URL }}      # e.g. https://your-app.example
        run: |
          curl -sS -X POST "$BASE_URL/scrape" -H "Content-Type: application/json" -d '{"role":"Electrician","location":"Adelaide","pages":1}'